######################## default configuration ####################
baseURL = "https://noorbuchi.netlify.app"
title = "Noor Buchi | Welcome to my website"
theme = "somrat"
# disable language
disableLanguages = [] # disable language from here

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/fontawesome/font-awesome.min.css"
[[params.plugins.css]]
link = "plugins/hover/hover.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/owl-carousel/owl.carousel.min.css"
[[params.plugins.css]]
link = "plugins/owl-carousel/owl.theme.default.min.css"
[[params.plugins.css]]
link = "plugins/text-animation/text-animation.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Rubik:300,400,500,700,900&display=swap"
[[params.plugins.css]]
link = "https://netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css"



# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/wow.min.js"
[[params.plugins.js]]
link = "plugins/text-animation/text-animation.js"
[[params.plugins.js]]
link = "plugins/jquery.waypoints.min.js"
[[params.plugins.js]]
link = "plugins/filterizr/jquery.filterizr.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/owl-carousel/owl.carousel.min.js"


############################## navigation ###############################

# main menu
[[menu.main]]
name = "Home"
URL = "#home"
weight = 1

[[menu.main]]
name = "About me"
URL = "#about"
weight = 2

[[menu.main]]
name = "Work Experience"
URL = "#experience"
weight = 3

[[menu.main]]
name = "Projects"
URL = "#portfolio"
weight = 4

# [[menu.main]]
# name = "Testimonial"
# URL = "#testimonial"
# weight = 5

# [[menu.main]]
# name = "Contact"
# URL = "#contact"
# weight = 6


#################### default parameters ################################
[params]
logo_light = "images/logo.png"
logo_dark = "images/logo-dark.png"
# Meta data
description = "Noor Buchi Personal website"
author = "Noor Buchi"
# contact form action
contact_form_action = "" # contact form works with https://formspree.io
# Google analytics
googleAnalytics =  "G-78SD7SK43C" # your id

# Preloader
[params.preloader]
enable = true
preloader = "images/preloaders/circles.svg" # use jpg, png, svg or gif format.

############################# social site ########################
[[params.social]]
icon = "fa-facebook-f" # fontawesome icon 4.7.0 : https://fontawesome.com/v4.7.0/icons/
link = ""

[[params.social]]
icon = "fa-twitter" # fontawesome icon 4.7.0 : https://fontawesome.com/v4.7.0/icons/
link = ""

[[params.social]]
icon = "fa-instagram" # fontawesome icon 4.7.0 : https://fontawesome.com/v4.7.0/icons/
link = ""

[[params.social]]
icon = "fa-github" # fontawesome icon 4.7.0 : https://fontawesome.com/v4.7.0/icons/
link = ""

[[params.social]]
icon = "fa-linkedin" # fontawesome icon 4.7.0 : https://fontawesome.com/v4.7.0/icons/
link = ""


################################### English language #####################################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "Home"
# copyright
copyright = "&copy; 2020 Noor Buchi | Powered By [Hugo](https://gohugo.io/) & [Somrat](https://themes.gohugo.io/somrat/)"


################################### French language #####################################
# [Languages.fr]
# languageName = "Fr"
# languageCode = "fr-fr"
# contentDir = "content/french"
# weight = 2
# home = "Accueil"
# # copyright
# copyright = "Copyright &copy; 2020 a hugo theme by [somrat](https://somrat.netlify.com)"
